const CATEGORIES_FETCH_ERROR="CATEGORIES_FETCH_ERROR";
const CATEGORIES_SUCCESS="CATEGORIES_SUCCESS";
const CATEGORIES_LOADING="CATEGORIES_LOADING";

export {
    CATEGORIES_FETCH_ERROR,
    CATEGORIES_SUCCESS,
    CATEGORIES_LOADING
}