const DEPARTMENTS_FETCH_ERROR="FETCH_ERROR";
const DEPARTMENTS_SUCCESS="DEPARTMENTS_SUCCESS";
const DEPARTMENTS_LOADING="DEPARTMENTS_SUCCESS";

export {
    DEPARTMENTS_FETCH_ERROR,
    DEPARTMENTS_SUCCESS,
    DEPARTMENTS_LOADING
}