//categories action types
const CATEGORIES_FETCH_ERROR="CATEGORIES_FETCH_ERROR";
const CATEGORIES_SUCCESS="CATEGORIES_SUCCESS";
const CATEGORIES_LOADING="CATEGORIES_LOADING";

//departments action types
const DEPARTMENTS_FETCH_ERROR="FETCH_ERROR";
const DEPARTMENTS_SUCCESS="DEPARTMENTS_SUCCESS";
const DEPARTMENTS_LOADING="DEPARTMENTS_SUCCESS";

//products action types
const PRODUCTS_FETCH_ERROR="PRODUCTS_FETCH_ERROR";
const PRODUCTS_SUCCESS="PRODUCTS_SUCCESS";
const PRODUCTS_LOADING="PRODUCTS_LOADING";

//signup action types
const SIGNUP_ERROR="SIGNUP_ERROR";
const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
const SIGNUP_LOADING="SIGNUP_LOADING";

//login action types
const LOGIN_ERROR="LOGIN_ERROR";
const LOGIN_SUCCESS="LOGIN_SUCCESS";
const LOGIN_LOADING="LOGIN_LOADING";

const types={
    categories:{
        CATEGORIES_FETCH_ERROR,
        CATEGORIES_SUCCESS,
        CATEGORIES_LOADING
    },
    departments:{
        DEPARTMENTS_FETCH_ERROR,
        DEPARTMENTS_SUCCESS,
        DEPARTMENTS_LOADING
    },
    products:{
        PRODUCTS_FETCH_ERROR,
        PRODUCTS_SUCCESS,
        PRODUCTS_LOADING
    },
    signup:{
        SIGNUP_SUCCESS,
        SIGNUP_LOADING,
        SIGNUP_ERROR
    },
    login:{
        LOGIN_ERROR,
        LOGIN_SUCCESS,
        LOGIN_LOADING
    }
};

export default types;